/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as AppRouteImport } from './routes/_app'
import { Route as AppIndexRouteImport } from './routes/_app.index'
import { Route as AppInvoicesRouteImport } from './routes/_app.invoices'
import { Route as AppProjectsRouteImport } from './routes/_app.projects'
import { Route as AppRateCardsRouteImport } from './routes/_app.rate-cards'
import { Route as AppTasksRouteImport } from './routes/_app.tasks'

const AppRoute = AppRouteImport.update({
  id: '/_app',
  getParentRoute: () => rootRouteImport,
} as any)
const AppIndexRoute = AppIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AppRoute,
} as any)
const AppInvoicesRoute = AppInvoicesRouteImport.update({
  id: '/invoices',
  path: '/invoices',
  getParentRoute: () => AppRoute,
} as any)
const AppProjectsRoute = AppProjectsRouteImport.update({
  id: '/projects',
  path: '/projects',
  getParentRoute: () => AppRoute,
} as any)
const AppRateCardsRoute = AppRateCardsRouteImport.update({
  id: '/rate-cards',
  path: '/rate-cards',
  getParentRoute: () => AppRoute,
} as any)
const AppTasksRoute = AppTasksRouteImport.update({
  id: '/tasks',
  path: '/tasks',
  getParentRoute: () => AppRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AppIndexRoute
  '/invoices': typeof AppInvoicesRoute
  '/projects': typeof AppProjectsRoute
  '/rate-cards': typeof AppRateCardsRoute
  '/tasks': typeof AppTasksRoute
}
export interface FileRoutesByTo {
  '/invoices': typeof AppInvoicesRoute
  '/projects': typeof AppProjectsRoute
  '/rate-cards': typeof AppRateCardsRoute
  '/tasks': typeof AppTasksRoute
  '/': typeof AppIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_app': typeof AppRouteWithChildren
  '/_app/invoices': typeof AppInvoicesRoute
  '/_app/projects': typeof AppProjectsRoute
  '/_app/rate-cards': typeof AppRateCardsRoute
  '/_app/tasks': typeof AppTasksRoute
  '/_app/': typeof AppIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/invoices' | '/projects' | '/rate-cards' | '/tasks'
  fileRoutesByTo: FileRoutesByTo
  to: '/invoices' | '/projects' | '/rate-cards' | '/tasks' | '/'
  id:
    | '__root__'
    | '/_app'
    | '/_app/invoices'
    | '/_app/projects'
    | '/_app/rate-cards'
    | '/_app/tasks'
    | '/_app/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AppRoute: typeof AppRouteWithChildren
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_app': {
      id: '/_app'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AppRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_app/': {
      id: '/_app/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AppIndexRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/invoices': {
      id: '/_app/invoices'
      path: '/invoices'
      fullPath: '/invoices'
      preLoaderRoute: typeof AppInvoicesRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/projects': {
      id: '/_app/projects'
      path: '/projects'
      fullPath: '/projects'
      preLoaderRoute: typeof AppProjectsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/rate-cards': {
      id: '/_app/rate-cards'
      path: '/rate-cards'
      fullPath: '/rate-cards'
      preLoaderRoute: typeof AppRateCardsRouteImport
      parentRoute: typeof AppRoute
    }
    '/_app/tasks': {
      id: '/_app/tasks'
      path: '/tasks'
      fullPath: '/tasks'
      preLoaderRoute: typeof AppTasksRouteImport
      parentRoute: typeof AppRoute
    }
  }
}

interface AppRouteChildren {
  AppInvoicesRoute: typeof AppInvoicesRoute
  AppProjectsRoute: typeof AppProjectsRoute
  AppRateCardsRoute: typeof AppRateCardsRoute
  AppTasksRoute: typeof AppTasksRoute
  AppIndexRoute: typeof AppIndexRoute
}

const AppRouteChildren: AppRouteChildren = {
  AppInvoicesRoute: AppInvoicesRoute,
  AppProjectsRoute: AppProjectsRoute,
  AppRateCardsRoute: AppRateCardsRoute,
  AppTasksRoute: AppTasksRoute,
  AppIndexRoute: AppIndexRoute,
}

const AppRouteWithChildren = AppRoute._addFileChildren(AppRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  AppRoute: AppRouteWithChildren,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
